name: Go

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-hash: ${{ steps.sha256.outputs.value }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build main.go
      
    - name: Calculate artifact sha
      id: sha256
      run: |
        SHA=$(sha256sum main | cut -d " " -f 1)
        echo "::set-output name=value::sha256:$SHA"
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: main
                
  generate-provenance:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Write git commit
      run: echo "git-commit:$GITHUB_SHA" >> provenance.txt

    - name: Write artifact hash
      run: echo artifact-hash:${{ needs.build.outputs.artifact-hash }} >> provenance.txt
      
      # this is not exact, perhaps we should extract this during the build "job"?
    - name: Write build time
      run: echo build-time:$(date -Ins) >> provenance.txt
      
      # run-id and run-number can be repeated if a run is repeated
    - name: Write github invocation information
      run: |
        echo gh-repository:$GITHUB_REPOSITORY >> provenance.txt
        echo gh-action:$GITHUB_ACTION >> provenance.txt
        echo gh-run-id:$GITHUB_RUN_ID >> provenance.txt
        echo gh-run-number:$GITHUB_RUN_NUMBER >> provenance.txt
        echo gh-actor:$GITHUB_ACTOR >> provenance.txt
    
    - name: debug (print env)
      run: env
      
    - name: Upload provenance
      uses: actions/upload-artifact@v2
      with:
        name: build-provenance
        path: provenance.txt
